#NAME: Juan Bai
#EMAIL: Daisybai66@yahoo.com
#ID: 105364754

#CC = gcc
#CFLAGS = -g -Wall -Wextra

default:
	rm -f lab3b
	ln lab3b.sh lab3b
	chmod u+x lab3b

dist:
	tar -czvf lab3b-105364754.tar.gz README Makefile lab3b.py lab3b.sh

clean:
	rm -f lab3b lab3b-105364754.tar.gz
